spring.application.name=scms-backend

# Production Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://dpg-d97rh0t8nd3s73eaqo30-a.ohio-postgres.render.com:5432/silicondb_crud_mja1?ssl=true
spring.datasource.username=silicondb_crud_user
spring.datasource.password=QFkylYwUoesN0ruoiKvnu6ehLG710AnY

# Production JPA Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Production Server Dynamic Port Allocation
server.port=${PORT:8080}

# CORS Configuration
cors.allowed-origins=http://localhost:4200,https://lambent-croissant-64abd6.netlify.app

# Connection Pool Settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10