spring.application.name=scms-backend

# Production Database (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://silicondb_crud_user:QFkylYwUoesNOruoiKvnu6ehLG710AnY@dpg-d97rh0t8nd3s73eaqo30-a.oregon-postgres.render.com/silicondb_crud_mja1?ssl=true
spring.datasource.username=silicondb_crud_user
spring.datasource.password=QFkylYwUoesNOruoiKvnu6ehLG710AnY
spring.datasource.driver-class-name=org.postgresql.Driver

# Production JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

server.port=8080

# CORS Configuration (We will update localhost to your Netlify URL later)

cors.allowed-origins=http://localhost:4200,https://lambent-croissant-64abd6.netlify.app
# Connection Pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10