spring.application.name=scms-backend

# Production Database (Render PostgreSQL)
spring.datasource.url=jdbc:postgresql://dpg-d944bpojs32c73dj70dg-a.ohio-postgres.render.com:5432/silicondb_crud
spring.datasource.username=silicondb_crud_user
spring.datasource.password=dobWVzD4gqxRy0IvFxYBnYW4jDSGn6KC
spring.datasource.driver-class-name=org.postgresql.Driver

# Production JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

server.port=8080

# CORS Configuration (We will update localhost to your Netlify URL later)
cors.allowed-origins=http://localhost:4200

# Connection Pool
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=10